### PR TITLE
Multilevel Autocomplete interface

### PR DESCRIPTION
**Pull request by programmarchy**
This PR implements the Multilevel Autocomplete interface described here: https://github.com/directus-labs/extension-experts/issues/10

**Features**

- The first step is always visible and can't be deleted. It can be either a `Web Request` or `List`.
- Additional steps can be added via the `Nested Steps` repeater field.
- Finally the `Payload` field takes a mustache template which transforms steps into a final result.
- Each step has a `resultsPath`, `textPath`, and `valuePath`.
- A `Web Request` step mimics the fields from the Autocomplete interface (url, trigger, rate, etc.)
- A `List` step is a repeater of items with `text` and `value`. Both string and json types are supported for `value`.
- Each step supports `placeholder`, `font`, `iconLeft`, and `iconRight`.
- The following scope is available to render a `url` for `Web Request` steps
  - **steps:** An item exists for each step. Will be `null` if step is not set.
  - **values:** A shortcut to `steps[].values`.
  - **value:** The value of the current step's input.
```
{
  steps: Array<{ text: string; value: string | object | null; } | null>;
  values: Array<string | object | null>;
  value: string;
}
```
 - The initial step is always enabled.
 - Nested steps are only enabled if their previous step has been set.
 - If a user updates a step, any subsequent steps will be reset.
 - The interface doesn't have any required fields, and can update its value incrementally without a complete set of entries.
 - When the interface has a value, a preview is generated as a list of "breadcrumbs" reflecting each step that has been set.

**Tests**

Here's a demo of the tests that were specified:

https://github.com/directus-labs/extensions/assets/622192/f7ddbd15-1100-4ca0-a63c-096c369b56d6

**Notes**

- The `List` does not actually use `resultsPath` since it's static and results will always be at the root.
- Could we rename the extension to `multilevel-autocomplete-api-interface` to match the naming of [`autocomplete-api`](https://github.com/directus/directus/tree/main/app/src/interfaces/input-autocomplete-api)?

### CODE REVIEW

**Comment by binaryben** [comment]
Hey @programmarchy, can you please add a commit to sign the CLA?

**Comment by programmarchy** [comment]
@binaryben Done #26

**Comment by phazonoverload** [comment]
Not fussy about the name, happy to do this.

**Comment by binaryben** [comment]
> Lmk if you want me to rebase this branch to resolve the merge conflict, taking main's version of pnpm-lock.yaml.

I've just used the Github tools to merge the changes from main in. I'm not fussed about the pnpm-lock.yaml file right now to be honest as I need to do a bit of work across all of the packages.

> Also, any thoughts on renaming multilevel-api-autocomplete to multilevel-autocomplete-api to match the convention established with autocomplete-api or would you prefer to keep the current name?

Yes, please go ahead and rename and then I will merge.

**Comment by programmarchy** [comment]
Did the rename already in the previous commit so should be good to go. 👍

**Review by binaryben — APPROVED** [review]

**Comment by binaryben** [comment]
Lovely, there is a few docs things needed for this but we will handle them as it may need a short video to explain. Good work.

**Pull request merged**
