### PR TITLE
Choropleth Map Panel

### PR DESCRIPTION
**Pull request by Arood**
Let me know if you experience any issues :)

### CODE REVIEW

**Comment by BlackDahlia313** [comment]
> Let me know if you experience any issues :)

I'm not reviewing this, but played around and this is really cool!

**Comment by phazonoverload** [comment]
@BlackDahlia313 Not at launch but we considered it. Getting 2nd level data in all countries is a bit tricky.

**Comment by Arood** [comment]
Technically it should be supported but like Kevin mentioned it might be tricky to get a general mapping of all states in all countries. It would also make the map quite huge with the required paths (that we might also have to extract ourselves). 

If someone is only interested in US states however, it should be really easy to fork it, I know there is data available for that.

An idea for a future update could be to be able to select different maps with different data mappings, i.e. World-map, US states, Europe, etc.

**Comment by BlackDahlia313** [comment]
Very cool to know! I like the idea of a future update where you could select. Ill keep tracking this. Good work!

**Review by HimoriTempest — COMMENTED** [review]
LGTM 🚀

**Review by phazonoverload — APPROVED** [review]

**Pull request merged**
