### PR TITLE
Experimental m2a interface

### PR DESCRIPTION
**Pull request by formfcw**
Everything should meet the requirements.

One small note: Since there is no clear indication which of the action buttons is a create button, I solved it by always taking the first one. So in the worst case, it will be labeled by "Add Existing" instead of "Create New", while providing the expected functionality.

### CODE REVIEW

**Review by binaryben — CHANGES_REQUESTED** [review]
The code for this is good and it functions well except for a small bug. The button matrix does not load on initial render of the page, but it loads after a refresh.

https://github.com/directus-labs/extensions/assets/12827556/19c97a5e-bae6-4ad2-94ed-23dcbc7894d1

Once that's fixed, I can approve and merge. Thanks

**Comment by binaryben** [comment]
> Since there is no clear indication which of the action buttons is a create button, I solved it by always taking the first one. So in the worst case, it will be labeled by "Add Existing" instead of "Create New", while providing the expected functionality.

Totally fine, thanks for letting us know about it

**Comment by formfcw** [comment]
> The code for this is good and it functions well except for a small bug. The button matrix does not load on initial render of the page, but it loads after a refresh.
> Experimental.m2a.interface.screen.recording.mov
> 
> Once that's fixed, I can approve and merge. Thanks

Fixed it (in a really hacky way)!

**Comment by binaryben** [comment]
> in a really hacky way

```
const maxTries = 20;
```

Works for me! 😊

**Review by binaryben — DISMISSED** [review]

**Review by binaryben — APPROVED** [review]

**Pull request merged**
