### PR TITLE
Gantt Chart Layout

### PR DESCRIPTION
**Pull request by Arood**
Adds a Gantt Chart Layout to Directus.

Notes:
- Uses a bundled version of the latest Frappe Gantt-library, as their npm action is broken and hasn't published the latest version. It also contains a minor fix to an issue that made it difficult to drag and drop items on some browsers (fixed by changing offsetX/Y to clientX/Y).
- Should work in both regular layouts and with selectMode, and I've tested running filters. This is my first layout extension so if you see something that I missed to test let me know!

### CODE REVIEW

**Review by ComfortablyCoding — CHANGES_REQUESTED** [review]
Feedback
1. The display unit (e.g. Day, Week, Month etc) does not retain its value between page refresh or navigation and always switches back to the default Day. This is not in sync with our built in layouts (e.g. Calender).
2. Some of the unit views are not "responsive" enough to fill the full layout Screenshot 2024-08-27 at 10 10 59 AM
3. If the `start date` of the task for a record is after the `end date` no items show, I would expect these to be filtered out and to show all the rest. Alternatively some error should be show to the user instead of in the console.
4. Any records without a `start_date` or `end_date` set are treated as having the start date before the end date. Due to point 3 this results in nothing showing, I would expect these to be filtered out.
5. Any records without a `start_date` or `end_date` seem to also crash the app.
6. For dragging `bar`/`start_date`/`end _date` only the unit that the current view is in should change. e.g. If I drag in the day view only the day value should change, not the time.
7. The bar seems to be off by a day in the day view, the hover value in the header does highlight the correct dates. For this record the dates are 11-16 Screenshot 2024-08-27 at 10 45 33 AM

**Comment by Arood** [comment]
1. Fixed
2. The library used isn't very responsive in this way as it's rendering svgs on the fly, but I found a configuration to extend the "padding" used, so it looks better on most common screen sizes
3-5. Added error handling now, opted to use the notification store to display any date interval errors so the view can still be used without it crashing.
6. Fixed
7. Should be fixed, seemed to be a CSS issue

**Comment by phazonoverload** [comment]
Any update on 5, 6, and 7 @Arood ?

**Comment by Arood** [comment]
@phazonoverload oh, didn't notice that Github ruined my formatting, they are all done

**Comment by ComfortablyCoding** [comment]
#### Feedback 
1. Upon re-review the time still changes when I change days, same for other units (changing month also changes days etc).
https://github.com/user-attachments/assets/f4d841ea-ebe9-41cf-aaf6-6488b856b070
2. The notice now displays on any change, we should maybe only display it on initial navigation/page load?

**Comment by Arood** [comment]
@ComfortablyCoding I noticed when testing that the issue might appear when using a Datetime-type, but it works as intended with Timestamp. Which seems to make sense as Datetime doesn't contain any timezone information, so I need to handle that. Does that description match your collection setup when testing?

**Comment by ComfortablyCoding** [comment]
> @ComfortablyCoding I noticed when testing that the issue might appear when using a Datetime-type, but it works as intended with Timestamp. Which seems to make sense as Datetime doesn't contain any timezone information, so I need to handle that. Does that description match your collection setup when testing?

Yes, that does seem to be the case.

**Comment by phazonoverload** [comment]
What's left to get this finished? It's running a bit behind.

**Comment by ComfortablyCoding** [comment]
> What's left to get this finished? It's running a bit behind.

The issues outlined in https://github.com/directus-labs/extensions/pull/45#issuecomment-2325232688

**Comment by Arood** [comment]
Oh, I was just looking at this and sent a new update :)

I believe I figured out how to fix the date issue, thanks for confirming the issue @ComfortablyCoding 

Regarding the errors I adjusted so the error shows once per set of items that errored (stored in sessionStorage so it resets for each session).

**Comment by ComfortablyCoding** [comment]
> Oh, I was just looking at this and sent a new update :)
> 
> I believe I figured out how to fix the date issue, thanks for confirming the issue @ComfortablyCoding
> 
> Regarding the errors I adjusted so the error shows once per set of items that errored (stored in sessionStorage so it resets for each session).

Sounds good, should issue `#3` regarding the app crashing be addressed as well in the last update?

**Comment by Arood** [comment]
@ComfortablyCoding Ah sorry, I missed that one. Should be easy enough to add a check there though, I'll fix it in a few mins

**Comment by Arood** [comment]
@ComfortablyCoding there we go! Added another error popup, handled the same way as the invalid date interval

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀 , thanks @Arood

**Comment by phazonoverload** [comment]
I'm sure you got this, but we held this back to release in October's set. :)

**Review by phazonoverload — APPROVED** [review]

**Pull request merged**
